// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: hello_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.Services {

  /// <summary>Holder for reflection information generated from hello_service.proto</summary>
  public static partial class HelloServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for hello_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HelloServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNoZWxsb19zZXJ2aWNlLnByb3RvGgtoZWxsby5wcm90bzI6CgxIZWxsb1Nl",
            "cnZpY2USKgoIU2F5SGVsbG8SDS5IZWxsb01lc3NhZ2UaDS5IZWxsb01lc3Nh",
            "Z2UiAEIRqgIOUHJvdG8uU2VydmljZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.Messages.HelloReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
