# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import hello_pb2 as hello__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello_service.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\016Proto.Services',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13hello_service.proto\x1a\x0bhello.proto2:\n\x0cHelloService\x12*\n\x08SayHello\x12\r.HelloMessage\x1a\r.HelloMessage\"\x00\x42\x11\xaa\x02\x0eProto.Servicesb\x06proto3'
  ,
  dependencies=[hello__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_HELLOSERVICE = _descriptor.ServiceDescriptor(
  name='HelloService',
  full_name='HelloService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=36,
  serialized_end=94,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='HelloService.SayHello',
    index=0,
    containing_service=None,
    input_type=hello__pb2._HELLOMESSAGE,
    output_type=hello__pb2._HELLOMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLOSERVICE)

DESCRIPTOR.services_by_name['HelloService'] = _HELLOSERVICE

# @@protoc_insertion_point(module_scope)
